### ISSUE TITLE
打开 OpenMV IDE 4.0.10  ，无法连接

### ISSUE THREAD

**Issue by zhuangbo214** [RCSN/openmv_for_hpm#2]
您好，我用 SEGGER Embedded Studio for RISC-V 6.30 在项目 debug 模式编译出  openmv_for_hpm.hex，
然后通过  hpmprogrammmer 烧写到 flash。
将主板的 USB0 连接到电脑，打开 OpenMV IDE 4.0.10  ，无法连接。
有可能是什么原因呢？

**Comment by RCSN** [comment]
设备管理器有没有Openmv的端口出现

**Comment by zhuangbo214** [comment]
好像没有设备弹出。


我试图通过 SEGGER Embedded Studio for RISC-V 6.30&nbsp; 里面，通过 GO方式烧录，
DEBUG USB 连接到电脑，BOOT1 和 BOOT0 拨到OFF，11
点击 GO 按钮 提示 GDB 设置有问题，
我的project 的 GDB server command line 设置是
E:\code\sdk_env1.3.0\tools\openocd\openocd.exe -f $(HPM_PRO_BASE)/boards/openocd/probes/ft2232.cfg -f $(HPM_PRO_BASE)/boards/openocd/soc/hpm6750-dual-core.cfg -f $(HPM_PRO_BASE)/boards/openocd/boards/cmsis_dap.cfg


我加了你的QQ，方便帮我看看吗？






BOBO
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RCSN/openmv_for_hpm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月8日(星期天) 下午5:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RCSN/openmv_for_hpm] 打开 OpenMV IDE 4.0.10  ，无法连接 (Issue #2)





 
设备管理器有没有Openmv的端口出现
